// This file is automatically generated.
// Please do not change this file!
export const body: string;
export const bodyLinks: string;
export const bodyLogo: string;
export const bodyLogoInner: string;
export const bodyRight: string;
export const bodySearch: string;
export const bodyTitle: string;
export const body_links: string;
export const body_logo: string;
export const body_logo_inner: string;
export const body_right: string;
export const body_search: string;
export const body_title: string;
export const container: string;
export const placeholder: string;
