// This file is automatically generated.
// Please do not change this file!
export const alertContainer: string;
export const alert_container: string;
export const articlesContainer: string;
export const articles_container: string;
export const content: string;
export const title: string;
